# Generated by Django 6.0.6 on 2026-07-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('course', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
