# Generated by Django 4.2.16 on 2026-08-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=100)),
            ],
        ),
    ]
