# Generated by Django 6.1 on 2026-08-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
