# Generated by Django 4.2.16 on 2026-07-22 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodiespot', '0002_cuisine_restaurant_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodiespot.cuisine'),
        ),
    ]
