# Generated by Django 6.0.6 on 2026-07-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.CharField(default='rajkot', max_length=20),
            preserve_default=False,
        ),
    ]
