# name=input("enter nmae")
# print("full name is", name )
# date=input("enter date")
# print("dob is ",date)
# mn=input("mn enter")
# print("mobile number is",mn)
# address=input("enter address ")
# print("address is ",address)
# print(r"fdgfgfbg rgrg rgegfgg")
print("He said \"Hello\"")